## NumPy array oluşturma (np.array, np.zeros, np.ones, np.arange, np.linspace..)

In [2]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

arr_z = np.zeros((4, 3))

arr_f = np.full((4, 5), 7)

arr_o = np.ones((3, 4))

arr_ar = np.arange(4)

arr_l = np.linspace(5, 20, 4)

arr_r = np.random.rand(3)

arr_r_i = np.random.randint(1, 45, 4)

print(arr, arr_z, arr_f, arr_o, arr_ar, arr_l, arr_r, arr_r_i, sep="\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[0 1 2 3]

[ 5. 10. 15. 20.]

[0.96101771 0.93016608 0.85788607]

[38 23  8  4]


## Basit işlemler:

In [5]:
s = arr + arr_o
t = arr_f * 2
diff = arr_r_i - arr_l
add = arr_r + 2
div = arr_o / 5
exp = arr_r_i ** 2
print(s, t, diff, add, div, exp, sep = "\n\n")

[[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]

[[14 14 14 14 14]
 [14 14 14 14 14]
 [14 14 14 14 14]
 [14 14 14 14 14]]

[ 33.  13.  -7. -16.]

[2.96101771 2.93016608 2.85788607]

[[0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2]]

[1444  529   64   16]


In [6]:
print("K = \n", np.add(arr, arr_r_i))

K = 
 [[39 25 11  8]
 [43 29 15 12]
 [47 33 19 16]]


# Broadcasting

Broadcasting → Farklı boyutlardaki diziler arasında matematiksel işlem yapmaya olanak tanır.
Yani tek tek elemanları eşleştirmene gerek kalmadan, NumPy otomatik olarak uyarlama yapar.

In [8]:
import numpy as np

In [9]:
k = np.array([1, 2, 3, 4, 5])

In [10]:
print(k + 5)

[ 6  7  8  9 10]


In [11]:
print(k - 2)

[-1  0  1  2  3]


In [12]:
print(k * 2)

[ 2  4  6  8 10]


In [13]:
print(k // 2)

[0 1 1 2 2]


In [14]:
mat_1 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
mat_2 = np.array([1, 2, 3]) 

mat_3 = np.array([[1],
                  [2],
                  [3]])
mat_4 = np.array([[1],[2],[3]])

In [15]:
print(mat_1 + mat_2)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [16]:
print(mat_2 + mat_3)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [17]:
b = np.array([1, 2, 3])
a = np.array([[1],[2],[3]])

print(mat_2 + mat_4)
# Burada a sütun, b satır gibi yayılıp 3x3 matris oldu.

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [18]:
mat = np.arange(16).reshape(4, 4)
print(mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [19]:
mat_bir = mat + 5
print(mat_bir)

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [20]:
mat_iki = mat_bir + np.array([1, 2, 3, 4])
print(mat_iki)

[[ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]
 [18 20 22 24]]


In [21]:
mat_uc = mat_iki + np.array([[10],[20],[30],[40]])
print(mat_uc)

[[16 18 20 22]
 [30 32 34 36]
 [44 46 48 50]
 [58 60 62 64]]


## Bazı Matematiksel İşlemler:

In [23]:
import numpy as np

x = np.array([[10, 12, 14, 16],
             [20, 22, 24, 26],
             [30, 32, 34, 36]])
y = np.arange(12).reshape((3, 4))

print("x = ", x, "y = ", y, sep = "\n\n")

x = 

[[10 12 14 16]
 [20 22 24 26]
 [30 32 34 36]]

y = 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
add = np.add(x, y)
print(add)

[[10 13 16 19]
 [24 27 30 33]
 [38 41 44 47]]


In [25]:
sb = np.subtract(x, y)
print(sb)

[[10 11 12 13]
 [16 17 18 19]
 [22 23 24 25]]


In [26]:
mlt = np.multiply(x, y)
print(mlt)

[[  0  12  28  48]
 [ 80 110 144 182]
 [240 288 340 396]]


In [27]:
div = np.divide(y, x)
print(div)

[[0.         0.08333333 0.14285714 0.1875    ]
 [0.2        0.22727273 0.25       0.26923077]
 [0.26666667 0.28125    0.29411765 0.30555556]]


In [28]:
sqrt_x = np.sqrt(x)
sqrt_y = np.sqrt(y)
print(sqrt_x, sqrt_y, sep = "\n\n")

[[3.16227766 3.46410162 3.74165739 4.        ]
 [4.47213595 4.69041576 4.89897949 5.09901951]
 [5.47722558 5.65685425 5.83095189 6.        ]]

[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]


In [29]:
exp_x = np.exp(x)
exp_y = np.exp(y)

print(exp_x, exp_y, sep = "\n\n")

[[2.20264658e+04 1.62754791e+05 1.20260428e+06 8.88611052e+06]
 [4.85165195e+08 3.58491285e+09 2.64891221e+10 1.95729609e+11]
 [1.06864746e+13 7.89629602e+13 5.83461743e+14 4.31123155e+15]]

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


In [30]:
log_x = np.log(x)

print(log_x)

[[2.30258509 2.48490665 2.63905733 2.77258872]
 [2.99573227 3.09104245 3.17805383 3.25809654]
 [3.40119738 3.4657359  3.52636052 3.58351894]]


In [31]:
pow_x = np.power(x, 2)
pow_y = np.power(y, 3)
pow_x_y = np.power(x, y)

print(pow_x, pow_y, pow_x_y, sep = "\n\n")

[[ 100  144  196  256]
 [ 400  484  576  676]
 [ 900 1024 1156 1296]]

[[   0    1    8   27]
 [  64  125  216  343]
 [ 512  729 1000 1331]]

[[          1          12         196        4096]
 [     160000     5153632   191102976  -558124416]
 [-1029996288           0  1723237376   104857600]]


## Trigonometrik İşlemler:
    np.sin(x)	
    np.cos(x)	
    np.tan(x)	
    np.arcsin(x)	
    np.arccos(x)	
    np.arctan(x)	
    np.deg2rad(x)	
    np.rad2deg(x)

In [33]:
x  = 60

In [34]:
s = np.sin(x)
c = np.cos(x)
t = np.tan(x)

print(s, c, t, sep = "\n")

-0.3048106211022167
-0.9524129804151563
0.320040389379563


In [35]:
y = 0.5

In [36]:
a_s = np.arcsin(y)
a_c = np.arccos(y)
a_t = np.arctan(y)

print(a_s, a_c, a_t, sep = "\n")

0.5235987755982989
1.0471975511965979
0.4636476090008061


In [37]:
z = 270

In [38]:
rad = np.deg2rad(z)
print(rad)

4.71238898038469


In [39]:
d = 7

In [40]:
deg = np.rad2deg(d)
print(deg)

401.07045659157626


## İstatistiksel İşlemler:
    np.mean(x)	
    np.median(x)	
    np.std(x)	
    np.var(x)
    np.min(x)	
    np.max(x)	
    np.argmin(x)	
    np.argmax(x)	
    np.percentile(x, q)

In [42]:
yas = np.array([10, 12, 24, 26, 28, 35, 44])

mean = np.mean(yas)	
med = np.median(yas)	
std = np.std(yas)	
var = np.var(yas)
minimum = np.min(yas)	
maximum = np.max(yas)	
min_I = np.argmin(yas)	
max_I = np.argmax(yas)	
percent_23 = np.percentile(yas, 23)

print("mean :", mean, "median :", med, "standart sapma :", std, "varyans :", var, "minimum değer :", minimum, "maksimum değer :", maximum, "minimum değerin indeksi :", min_I, "maksimum değerin indeksi :", max_I, "yüzdelik değeri :", percent_23, sep = "\n")



mean :
25.571428571428573
median :
26.0
standart sapma :
11.108004100739286
varyans :
123.3877551020408
minimum değer :
10
maksimum değer :
44
minimum değerin indeksi :
0
maksimum değerin indeksi :
6
yüzdelik değeri :
16.560000000000002


## Yuvarlama Fonksiyonları:

    | Fonksiyon        | Açıklama                                      |
    | ---------------- | --------------------------------------------- |
    | `np.round(x, n)` | Elemanları n basamak olacak şekilde yuvarlar. |
    | `np.floor(x)`    | Aşağıya yuvarlar (en küçük tam sayıya).       |
    | `np.ceil(x)`     | Yukarıya yuvarlar (en büyük tam sayıya).      |
    | `np.trunc(x)`    | Ondalık kısmı atar (keser).                   |


In [44]:
ondalikli_sayilar = np.array([5.7, 6.4, 7.3, 9.5, 11.9, 23.47, 28.51])

a = np.round(ondalikli_sayilar)
b = np.floor(ondalikli_sayilar)
c = np.ceil(ondalikli_sayilar)
d = np.trunc(ondalikli_sayilar)

print("a: ", a, "\nb: ", b, "\nc: ", c, "\nd: ", d)

a:  [ 6.  6.  7. 10. 12. 23. 29.] 
b:  [ 5.  6.  7.  9. 11. 23. 28.] 
c:  [ 6.  7.  8. 10. 12. 24. 29.] 
d:  [ 5.  6.  7.  9. 11. 23. 28.]
